server:
  port: 8501

spring:
  application:
    name: account-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spcloud:
  cassandra:
    contact:
      point: 127.0.0.1
    port: 9042
    keyspace:
      name: springcloud
    schema-action: CREATE_IF_NOT_EXISTS

    username: cassandra
    password: cassandra
